/* ===================================================================
   科目一教考 · 知识点 HTML 内容
   - 将原 docs/knowledge.md 的内容固化为结构化 HTML 字符串
   - 使用语义化标签 + 双类名策略：
       * know-* 为新语义类名（便于后续样式扩展）
       * md-*   为兼容现有 css/style.css 中 .knowledge-content 样式的类名
   - 全局变量：KNOWLEDGE_HTML
   - 消费方式：app.js 中 renderKnowledge() 直接写入 #knowledge-content 的 innerHTML
   =================================================================== */
'use strict';

/* global KNOWLEDGE_HTML */
/* eslint-disable max-len */

/**
 * 知识点 HTML 字符串
 * 结构：每章以 <section class="know-chapter md-chapter" id="chapter-N"> 包裹
 *      章标题 <h2 class="know-chapter-title md-h md-h2">
 *      节标题 <h3 class="know-section-title md-h md-h3">
 *      子节标题 <h4 class="know-subsection-title md-h md-h4">
 *      表格 <table class="know-table md-table">
 *      口诀 <div class="know-mnemonic md-quote">
 *      提示 <blockquote class="md-quote know-tip">
 *      警告 <blockquote class="md-quote know-warning">
 */
var KNOWLEDGE_HTML = [
  /* ============ 文档导语 ============ */
  '<div class="md-quote know-tip">',
  '基于公安部令第163号《机动车驾驶证申领和使用规定》及2026年最新驾考大纲；',
  '系统化知识点讲解，覆盖交通法规、安全驾驶、信号识别、应急处置全领域。',
  '</div>',

  /* ============ 第一章 ============ */
  '<section class="know-chapter md-chapter" id="chapter-1">',
  '<h2 class="know-chapter-title md-h md-h2">一、交通信号与标志</h2>',

  '<h3 class="know-section-title md-h md-h3">1.1 交通信号灯</h3>',
  '<p class="md-p">交通信号灯是道路交通的基本指挥信号，由红、黄、绿三种颜色组成，遵循"红灯停、绿灯行、黄灯警告"的基本原则。</p>',

  '<h4 class="know-subsection-title md-h md-h4">机动车信号灯</h4>',
  '<ul class="md-ul">',
  '<li><strong>绿灯亮</strong>：准许车辆通行，但转弯车辆不得妨碍直行车辆和行人</li>',
  '<li><strong>黄灯亮</strong>：已越过停止线的车辆可继续通行，未越过的应减速停车</li>',
  '<li><strong>红灯亮</strong>：禁止车辆通行，右转弯车辆在不妨碍被放行车辆和行人情况下可通行</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">方向指示信号灯</h4>',
  '<p class="md-p">箭头方向信号灯分为左转、直行、右转三种，绿色箭头表示准许沿该方向行驶，红色箭头表示禁止该方向行驶。</p>',

  '<h4 class="know-subsection-title md-h md-h4">车道信号灯</h4>',
  '<ul class="md-ul">',
  '<li><strong>绿色向下箭头</strong>：本车道准许通行</li>',
  '<li><strong>红色叉形或斜杠</strong>：本车道禁止通行</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">非机动车与行人信号灯</h4>',
  '<p class="md-p">非机动车信号灯采用自行车图案，行人信号灯采用行人图案。红灯禁止通行，绿灯准许通行，绿灯闪烁表示即将变为红灯。</p>',

  '<h3 class="know-section-title md-h md-h3">1.2 交通标志分类</h3>',
  '<p class="md-p">交通标志按功能分为七大类，每类有独特形状与颜色特征。</p>',

  '<h4 class="know-subsection-title md-h md-h4">警告标志</h4>',
  '<ul class="md-ul">',
  '<li><strong>颜色</strong>：黄底、黑边、黑图案</li>',
  '<li><strong>形状</strong>：顶角朝上的等边三角形</li>',
  '<li><strong>作用</strong>：警告车辆、行人注意危险地点</li>',
  '<li><strong>常见标志</strong>：急弯路、连续弯路、陡坡、窄路、注意行人、注意儿童、注意牲畜</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">禁令标志</h4>',
  '<ul class="md-ul">',
  '<li><strong>颜色</strong>：白底、红圈、红杠、黑图案（解除禁令标志为白底、黑圈、黑图案）</li>',
  '<li><strong>形状</strong>：圆形（停车让行为八角形，减速让行为倒三角形）</li>',
  '<li><strong>作用</strong>：禁止或限制车辆、行人交通行为</li>',
  '<li><strong>常见标志</strong>：禁止通行、禁止驶入、禁止停车、限制速度、限制高度</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">指示标志</h4>',
  '<ul class="md-ul">',
  '<li><strong>颜色</strong>：蓝底、白图案</li>',
  '<li><strong>形状</strong>：圆形、长方形、正方形</li>',
  '<li><strong>作用</strong>：指示车辆、行人行进</li>',
  '<li><strong>常见标志</strong>：直行、向左转弯、靠右侧道路行驶、单行路、步行街、允许掉头</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">指路标志</h4>',
  '<ul class="md-ul">',
  '<li><strong>颜色</strong>：一般道路为蓝底白图案，高速公路为绿底白图案，旅游区为棕底白图案</li>',
  '<li><strong>形状</strong>：长方形（地点识别标志除外）</li>',
  '<li><strong>作用</strong>：传递道路方向、地点、距离信息</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">其他标志</h4>',
  '<ul class="md-ul">',
  '<li><strong>作业区标志</strong>：橘黄底、黑图案</li>',
  '<li><strong>辅助标志</strong>：白底、黑字、黑边框，附设在主标志下</li>',
  '<li><strong>告示标志</strong>：白底、黑字，提示驾驶员注意</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">1.3 交通标线</h3>',
  '<p class="md-p">交通标线按功能分为指示标线、禁止标线、警告标线三类。</p>',

  '<h4 class="know-subsection-title md-h md-h4">指示标线</h4>',
  '<ul class="md-ul">',
  '<li><strong>白色虚线</strong>：分隔同向行驶的交通流，准许跨越</li>',
  '<li><strong>白色实线</strong>：分隔同向行驶的交通流，不准跨越</li>',
  '<li><strong>黄色虚线</strong>：分隔对向行驶的交通流，准许一侧跨越</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">禁止标线</h4>',
  '<ul class="md-ul">',
  '<li><strong>黄色实线</strong>：分隔对向行驶的交通流，严禁跨越</li>',
  '<li><strong>双黄实线</strong>：严格禁止车辆压线或跨越</li>',
  '<li><strong>导流线</strong>：白色V形线或斜纹线，车辆不得压线或越线行驶</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">警告标线</h4>',
  '<ul class="md-ul">',
  '<li><strong>路面障碍物标线</strong>：提醒前方有障碍物</li>',
  '<li><strong>减速标线</strong>：提醒车辆减速</li>',
  '<li><strong>立面标记</strong>：提醒驾驶员注意车道边缘</li>',
  '</ul>',
  '</section>',

  /* ============ 第二章 ============ */
  '<section class="know-chapter md-chapter" id="chapter-2">',
  '<h2 class="know-chapter-title md-h md-h2">二、道路交通安全法规</h2>',

  '<h3 class="know-section-title md-h md-h3">2.1 机动车驾驶证</h3>',

  '<h4 class="know-subsection-title md-h md-h4">驾驶证类型与准驾车型</h4>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>驾照类型</th><th>准驾车型</th><th>说明</th>',
  '</tr></thead><tbody>',
  '<tr><td>A1</td><td>大型客车</td><td>车长≥6米或核载≥20人</td></tr>',
  '<tr><td>A2</td><td>牵引车</td><td>重型、中型全挂、半挂汽车</td></tr>',
  '<tr><td>A3</td><td>城市公交车</td><td>核载10人以上的城市公共汽车</td></tr>',
  '<tr><td>B1</td><td>中型客车</td><td>核载10人以上、19人以下</td></tr>',
  '<tr><td>B2</td><td>大型货车</td><td>重型、中型载货汽车</td></tr>',
  '<tr><td>C1</td><td>小型汽车</td><td>小型、微型载客汽车及轻型载货汽车</td></tr>',
  '<tr><td>C2</td><td>小型自动挡汽车</td><td>仅小型、微型自动挡载客汽车</td></tr>',
  '<tr><td>C3</td><td>低速载货汽车</td><td>低速载货汽车及三轮汽车</td></tr>',
  '<tr><td>C4</td><td>三轮汽车</td><td>三轮汽车</td></tr>',
  '<tr><td>C5</td><td>残疾人专用汽车</td><td>残疾人专用小型、微型自动挡载客汽车</td></tr>',
  '</tbody></table></div>',

  '<h4 class="know-subsection-title md-h md-h4">驾驶证有效期</h4>',
  '<ul class="md-ul">',
  '<li><strong>初次领证</strong>：有效期6年</li>',
  '<li><strong>第二次换证</strong>：有效期10年（6年内每个记分周期均未达到12分）</li>',
  '<li><strong>第三次换证</strong>：长期有效（10年内每个记分周期均未达到12分）</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">驾驶证换证</h4>',
  '<p class="md-p">驾驶证期满换证应在有效期满前90日内办理。需提交身份证明、驾驶证、身体条件证明。</p>',

  '<h3 class="know-section-title md-h md-h3">2.2 记分管理制度（公安部令第163号 · 2022年4月1日实施 · 2026年7月最新版）</h3>',

  '<h4 class="know-subsection-title md-h md-h4">记分周期</h4>',
  '<p class="md-p">记分周期为12个月，满分为12分，从机动车驾驶证初次领取之日起计算。</p>',

  '<h4 class="know-subsection-title md-h md-h4">记分分值</h4>',
  '<p class="md-p">记分分为5个档次：1分、3分、6分、9分、12分（取消原2分档）。</p>',

  '<h4 class="know-subsection-title md-h md-h4">超速扣分速记表（小型载客汽车）</h4>',
  '<div class="know-mnemonic md-quote">口诀：<strong>普36高6满</strong></div>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>道路类型</th><th>超速&lt;20%</th><th>超速20%-50%</th><th>超速≥50%</th>',
  '</tr></thead><tbody>',
  '<tr><td>普通道路（非高速/快速路）</td><td>不记分</td><td><strong>3分</strong></td><td><strong>6分</strong></td></tr>',
  '<tr><td>高速公路/城市快速路</td><td>不记分</td><td><strong>6分</strong></td><td><strong>12分（满）</strong></td></tr>',
  '</tbody></table></div>',
  '<blockquote class="md-quote know-warning">校车、中型以上载客载货汽车、危险物品运输车辆超速处罚更严：高速超速20%以上即记12分。</blockquote>',

  '<h4 class="know-subsection-title md-h md-h4">超载扣分速记表</h4>',
  '<div class="know-mnemonic md-quote">口诀：<strong>七上69七下36</strong> / <strong>校车20%分界扣6满</strong></div>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>车辆类型</th><th>超员&lt;20%</th><th>超员20%-50%</th><th>超员≥50%</th><th>超员≥100%</th>',
  '</tr></thead><tbody>',
  '<tr><td>7座以下载客汽车</td><td>3分</td><td>6分</td><td>9分</td><td>—</td></tr>',
  '<tr><td>7座以上载客汽车</td><td>3分/6分</td><td>6分/9分</td><td>9分/12分</td><td>12分</td></tr>',
  '<tr><td>校车/营运客车</td><td><strong>6分</strong></td><td><strong>12分</strong></td><td>12分</td><td>12分</td></tr>',
  '</tbody></table></div>',

  '<h4 class="know-subsection-title md-h md-h4">肇事逃逸扣分</h4>',
  '<div class="know-mnemonic md-quote">口诀：<strong>轻微逃逸6重伤逃逸满</strong></div>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>逃逸情形</th><th>记分</th><th>说明</th>',
  '</tr></thead><tbody>',
  '<tr><td>造成轻微伤/财产损失后逃逸（不构成犯罪）</td><td><strong>6分</strong></td><td>轻微逃逸</td></tr>',
  '<tr><td>造成轻伤以上/死亡后逃逸（不构成犯罪）</td><td><strong>12分</strong></td><td>重伤逃逸</td></tr>',
  '<tr><td>交通肇事逃逸构成犯罪</td><td>终身禁驾</td><td>刑事追责</td></tr>',
  '</tbody></table></div>',

  '<h4 class="know-subsection-title md-h md-h4">号牌违法扣分</h4>',
  '<div class="know-mnemonic md-quote">口诀：<strong>号牌不按3未挂9伪造12</strong></div>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>违法情形</th><th>记分</th>',
  '</tr></thead><tbody>',
  '<tr><td>不按规定安装号牌</td><td>3分</td></tr>',
  '<tr><td>未悬挂/故意遮挡/污损号牌</td><td>9分</td></tr>',
  '<tr><td>伪造/变造号牌</td><td>12分</td></tr>',
  '</tbody></table></div>',

  '<h4 class="know-subsection-title md-h md-h4">道路行驶扣分</h4>',
  '<div class="know-mnemonic md-quote">口诀：<strong>不按车道3不按灯6</strong></div>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>违法情形</th><th>记分</th>',
  '</tr></thead><tbody>',
  '<tr><td>不按规定车道行驶</td><td>3分</td></tr>',
  '<tr><td>不按交通信号灯通行（闯红灯）</td><td>6分</td></tr>',
  '<tr><td>违反禁令标志/禁止标线</td><td>1分</td></tr>',
  '<tr><td>不按规定让行</td><td>3分</td></tr>',
  '<tr><td>不按规定超车</td><td>3分</td></tr>',
  '</tbody></table></div>',

  '<h4 class="know-subsection-title md-h md-h4">危险品运输扣分</h4>',
  '<div class="know-mnemonic md-quote">口诀：<strong>危险未挂扣6分</strong></div>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>违法情形</th><th>记分</th>',
  '</tr></thead><tbody>',
  '<tr><td>危险品运输车未悬挂/未放置警告标志</td><td>6分</td></tr>',
  '<tr><td>未悬挂警告标志</td><td>3分</td></tr>',
  '<tr><td>未悬挂警示标志</td><td>6分</td></tr>',
  '</tbody></table></div>',

  '<h4 class="know-subsection-title md-h md-h4">准驾车型扣分</h4>',
  '<div class="know-mnemonic md-quote">口诀：<strong>准驾不符扣9分</strong></div>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>违法情形</th><th>记分</th><th>说明</th>',
  '</tr></thead><tbody>',
  '<tr><td>驾驶与准驾车型不符的机动车</td><td><strong>9分</strong></td><td>2022新规从12分降为9分</td></tr>',
  '<tr><td>未取得校车资格驾驶校车</td><td>9分</td><td>—</td></tr>',
  '</tbody></table></div>',

  '<h4 class="know-subsection-title md-h md-h4">高速公路违法扣分</h4>',
  '<div class="know-mnemonic md-quote">口诀：<strong>高速慢3占6停9逆12</strong></div>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>违法情形</th><th>记分</th>',
  '</tr></thead><tbody>',
  '<tr><td>低于最低时速行驶</td><td>3分</td></tr>',
  '<tr><td>违法占用应急车道</td><td>6分</td></tr>',
  '<tr><td>违法停车</td><td>9分</td></tr>',
  '<tr><td>倒车/逆行/穿越中央分隔带掉头</td><td>12分</td></tr>',
  '</tbody></table></div>',

  '<h4 class="know-subsection-title md-h md-h4">记12分的违法行为（完整列表）</h4>',
  '<ul class="md-ul">',
  '<li>饮酒后驾驶机动车</li>',
  '<li>造成致人轻伤以上交通事故后逃逸，尚不构成犯罪</li>',
  '<li>使用伪造、变造的机动车号牌、行驶证、驾驶证、校车标牌或使用其他机动车号牌、行驶证</li>',
  '<li>驾驶校车、公路客运汽车、旅游客运汽车载人超过核定人数20%以上，或驾驶其他载客汽车载人超过核定人数100%以上</li>',
  '<li>驾驶校车、中型以上载客载货汽车、危险物品运输车辆在高速公路、城市快速路上行驶超过规定时速20%以上，或驾驶其他机动车超过规定时速50%以上</li>',
  '<li>在高速公路、城市快速路上倒车、逆行、穿越中央分隔带掉头</li>',
  '<li>代替实际机动车驾驶人接受交通违法行为处罚和记分牟取经济利益</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">记9分的违法行为（完整列表）</h4>',
  '<ul class="md-ul">',
  '<li>驾驶7座以上载客汽车载人超过核定人数50%以上未达到100%</li>',
  '<li>驾驶校车、中型以上载客载货汽车、危险物品运输车辆在高速公路、城市快速路以外的道路上行驶超过规定时速50%以上</li>',
  '<li>驾驶机动车在高速公路、城市快速路违法占用应急车道行驶</li>',
  '<li>驾驶未悬挂机动车号牌或故意遮挡、污损机动车号牌的机动车上道路行驶</li>',
  '<li><strong>驾驶与准驾车型不符的机动车</strong>（2022新规从12分调整为9分）</li>',
  '<li>未取得校车驾驶资格驾驶校车</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">记6分的违法行为（完整列表）</h4>',
  '<ul class="md-ul">',
  '<li>驾驶校车、中型以上载客载货汽车、危险物品运输车辆在高速公路、城市快速路上行驶超过规定时速未达到20%，或在其他道路超过规定时速20%以上未达到50%</li>',
  '<li>驾驶机动车载运危险化学品未经批准进入危险化学品运输车辆限制通行区域</li>',
  '<li>机动车驾驶证被暂扣期间驾驶机动车</li>',
  '<li>驾驶机动车在高速公路、城市快速路以外的道路上逆行</li>',
  '<li>驾驶机动车不按交通信号灯规定通行</li>',
  '<li><strong>造成轻微伤或财产损失的交通事故后逃逸，尚不构成犯罪</strong></li>',
  '<li>违法占用应急车道行驶</li>',
  '<li>不按规定避让校车</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">记3分的违法行为（完整列表）</h4>',
  '<ul class="md-ul">',
  '<li>驾驶机动车在高速公路、城市快速路以外的道路上行驶超过规定时速20%以上未达到50%</li>',
  '<li>驾驶机动车载货长度、宽度、高度超过规定</li>',
  '<li>驾驶机动车不按规定超车、让行或逆向行驶</li>',
  '<li>驾驶机动车行经人行横道不按规定减速、停车、避让行人</li>',
  '<li>驾驶机动车拨打接听手持电话或有其他妨碍安全驾驶的行为</li>',
  '<li>不按规定车道行驶</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">记1分的违法行为（完整列表）</h4>',
  '<ul class="md-ul">',
  '<li>驾驶机动车不按规定使用灯光</li>',
  '<li>驾驶机动车不按规定会车</li>',
  '<li>驾驶机动车载货长度、宽度、高度超过规定（轻微）</li>',
  '<li>驾驶未按规定定期进行安全技术检验的机动车上道路行驶</li>',
  '<li>违反禁令标志、禁止标线指示</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">2.3 违法行为处罚</h3>',

  '<h4 class="know-subsection-title md-h md-h4">处罚种类</h4>',
  '<ul class="md-ul">',
  '<li>警告</li>',
  '<li>罚款</li>',
  '<li>暂扣机动车驾驶证</li>',
  '<li>吊销机动车驾驶证</li>',
  '<li>行政拘留</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">饮酒驾驶处罚</h4>',
  '<ul class="md-ul">',
  '<li><strong>饮酒驾驶</strong>（血液酒精含量20-80mg/100ml）：暂扣驾驶证6个月，罚款1000-2000元，记12分</li>',
  '<li><strong>醉酒驾驶</strong>（血液酒精含量≥80mg/100ml）：吊销驾驶证，5年内不得重新取得，依法追究刑事责任</li>',
  '<li><strong>饮酒驾驶营运车</strong>：拘留15日，罚款5000元，吊销驾驶证，5年内不得重新取得</li>',
  '<li><strong>醉酒驾驶营运车</strong>：吊销驾驶证，10年内不得重新取得，终生不得驾驶营运车</li>',
  '</ul>',
  '</section>',

  /* ============ 第三章 ============ */
  '<section class="know-chapter md-chapter" id="chapter-3">',
  '<h2 class="know-chapter-title md-h md-h2">三、安全驾驶基础</h2>',

  '<h3 class="know-section-title md-h md-h3">3.1 车辆起步与停车</h3>',

  '<h4 class="know-subsection-title md-h md-h4">起步操作流程</h4>',
  '<ol class="md-ol">',
  '<li>调整座椅、后视镜，系好安全带</li>',
  '<li>检查仪表盘各项指示</li>',
  '<li>踩离合器（手动挡）或踩刹车（自动挡）</li>',
  '<li>挂入挡位</li>',
  '<li>观察后视镜并开启左转向灯</li>',
  '<li>鸣喇叭（禁鸣区域除外）</li>',
  '<li>平稳起步，汇入车流</li>',
  '</ol>',

  '<h4 class="know-subsection-title md-h md-h4">停车操作规范</h4>',
  '<ul class="md-ul">',
  '<li>选择允许停车的地点</li>',
  '<li>开启右转向灯，提前减速</li>',
  '<li>观察右后视镜确认安全</li>',
  '<li>平稳停车，拉紧手刹</li>',
  '<li>关闭转向灯，熄火</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">禁止停车地点</h4>',
  '<ul class="md-ul">',
  '<li>设有禁止停车标志、标线的路段</li>',
  '<li>机动车道与非机动车道、人行道之间设有隔离设施的路段</li>',
  '<li>人行横道、施工地段</li>',
  '<li>交叉路口、铁路道口、急弯路、宽度不足4米的窄路、桥梁、陡坡、隧道及距离上述地点50米以内的路段</li>',
  '<li>公共汽车站、急救站、加油站、消防栓或消防队门前及距离上述地点30米以内的路段</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">3.2 行驶速度规定</h3>',

  '<h4 class="know-subsection-title md-h md-h4">一般道路限速</h4>',
  '<ul class="md-ul">',
  '<li><strong>没有中心线的道路</strong>：城市道路30km/h，公路40km/h</li>',
  '<li><strong>同方向只有1条机动车道</strong>：城市道路50km/h，公路70km/h</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">特殊路段限速</h4>',
  '<ul class="md-ul">',
  '<li><strong>进出非机动车道、通过铁路道口、急弯路、窄路、窄桥</strong>：最高30km/h</li>',
  '<li><strong>掉头、转弯、下陡坡</strong>：最高30km/h</li>',
  '<li><strong>冰雪、泥泞道路</strong>：最高30km/h</li>',
  '<li><strong>牵引故障车</strong>：最高30km/h</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">高速公路限速</h4>',
  '<ul class="md-ul">',
  '<li><strong>最低车速</strong>：不得低于60km/h</li>',
  '<li><strong>小型载客汽车最高车速</strong>：120km/h</li>',
  '<li><strong>其他机动车最高车速</strong>：100km/h</li>',
  '<li><strong>摩托车最高车速</strong>：80km/h</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">高速公路车道车速</h4>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>车道</th><th>最低车速</th>',
  '</tr></thead><tbody>',
  '<tr><td>最左侧车道（双车道）</td><td>100km/h</td></tr>',
  '<tr><td>最左侧车道（三车道以上）</td><td>110km/h</td></tr>',
  '<tr><td>中间车道</td><td>90km/h</td></tr>',
  '<tr><td>最右车道</td><td>60km/h</td></tr>',
  '</tbody></table></div>',

  '<h3 class="know-section-title md-h md-h3">3.3 安全车距</h3>',

  '<h4 class="know-subsection-title md-h md-h4">影响安全车距的因素</h4>',
  '<ul class="md-ul">',
  '<li>行驶速度：速度越快，所需车距越大</li>',
  '<li>天气条件：雨雪雾天应加大车距</li>',
  '<li>路面状况：湿滑路面应加大车距</li>',
  '<li>车辆状况：制动性能影响车距</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">车距保持原则</h4>',
  '<ul class="md-ul">',
  '<li><strong>干燥路面</strong>：车速的公里数对应米数（如60km/h保持60米）</li>',
  '<li><strong>湿滑路面</strong>：加大至干燥路面的1.5倍</li>',
  '<li><strong>冰雪路面</strong>：加大至干燥路面的3倍以上</li>',
  '<li><strong>高速公路</strong>：时速100km/h时保持100米以上，时速70km/h时保持70米以上</li>',
  '</ul>',
  '</section>',

  /* ============ 第四章 ============ */
  '<section class="know-chapter md-chapter" id="chapter-4">',
  '<h2 class="know-chapter-title md-h md-h2">四、高速公路驾驶</h2>',

  '<h3 class="know-section-title md-h md-h3">4.1 驶入高速公路</h3>',

  '<h4 class="know-subsection-title md-h md-h4">匝道行驶</h4>',
  '<ul class="md-ul">',
  '<li>在匝道上加速至60km/h以上</li>',
  '<li>注意观察主路车流情况</li>',
  '<li>开启左转向灯准备汇入</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">加速车道</h4>',
  '<ul class="md-ul">',
  '<li>在加速车道充分加速</li>',
  '<li>不得在加速车道减速或停车</li>',
  '<li>寻找安全空隙汇入主路</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">汇入主路</h4>',
  '<ul class="md-ul">',
  '<li>开启左转向灯</li>',
  '<li>观察左后视镜和盲区</li>',
  '<li>平稳汇入，不得妨碍主路车辆正常行驶</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">4.2 高速公路行驶</h3>',

  '<h4 class="know-subsection-title md-h md-h4">车道选择</h4>',
  '<ul class="md-ul">',
  '<li>双向四车道：大型车走右车道，小型车走左车道</li>',
  '<li>双向六车道：最左为超车道，中间为小型车道，最右为大型车道</li>',
  '<li>不得长时间占用最左侧车道</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">超车规范</h4>',
  '<ul class="md-ul">',
  '<li>超车前观察前方、后方交通情况</li>',
  '<li>开启左转向灯，变更至左侧车道</li>',
  '<li>超车后开启右转向灯，驶回原车道</li>',
  '<li>不得从右侧超车</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">跟车距离</h4>',
  '<ul class="md-ul">',
  '<li>时速100km/h：保持100米以上</li>',
  '<li>时速70km/h：保持70米以上</li>',
  '<li>遇冰雪、雾天等恶劣天气：加大至200米以上</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">4.3 驶出高速公路</h3>',

  '<h4 class="know-subsection-title md-h md-h4">驶出流程</h4>',
  '<ul class="md-ol">',
  '<li>提前1-2公里观察出口预告标志</li>',
  '<li>开启右转向灯，进入减速车道</li>',
  '<li>在减速车道减速至60km/h以下</li>',
  '<li>经匝道驶出收费站</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">注意事项</h4>',
  '<ul class="md-ul">',
  '<li>不得在出口处紧急制动</li>',
  '<li>不得在加速车道或减速车道超车</li>',
  '<li>错过出口应继续行驶至下一出口，严禁倒车、掉头</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">4.4 高速公路特殊规定</h3>',

  '<h4 class="know-subsection-title md-h md-h4">禁止行为</h4>',
  '<ul class="md-ul">',
  '<li>倒车、逆行、穿越中央分隔带掉头</li>',
  '<li>在匝道、加速车道、减速车道超车</li>',
  '<li>骑、轧车行道分界线</li>',
  '<li>非紧急情况下占用应急车道</li>',
  '<li>试车、学习驾驶</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">故障处理</h4>',
  '<ul class="md-ul">',
  '<li>立即开启危险报警闪光灯</li>',
  '<li>将车移至应急车道或紧急停车带</li>',
  '<li>在车后方150米处设置警告标志</li>',
  '<li>夜间还应开启示廓灯和后位灯</li>',
  '<li>人员迅速撤离至护栏外</li>',
  '<li>报警求助</li>',
  '</ul>',
  '</section>',

  /* ============ 第五章 ============ */
  '<section class="know-chapter md-chapter" id="chapter-5">',
  '<h2 class="know-chapter-title md-h md-h2">五、夜间与特殊天气驾驶</h2>',

  '<h3 class="know-section-title md-h md-h3">5.1 夜间驾驶</h3>',

  '<h4 class="know-subsection-title md-h md-h4">灯光使用</h4>',
  '<ul class="md-ul">',
  '<li><strong>有路灯</strong>：使用近光灯</li>',
  '<li><strong>无路灯</strong>：使用远光灯，会车时改用近光灯</li>',
  '<li><strong>会车</strong>：距对向车150米外改用近光灯</li>',
  '<li><strong>超车</strong>：交替使用远近光灯示意</li>',
  '<li><strong>通过路口</strong>：交替使用远近光灯示意</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">夜间行驶注意事项</h4>',
  '<ul class="md-ul">',
  '<li>减速慢行，保持安全车距</li>',
  '<li>注意观察行人、非机动车</li>',
  '<li>避免长时间注视对向车灯</li>',
  '<li>疲劳时及时停车休息</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">5.2 雨天驾驶</h3>',

  '<h4 class="know-subsection-title md-h md-h4">雨天行车特点</h4>',
  '<ul class="md-ul">',
  '<li>路面湿滑，制动距离延长</li>',
  '<li>视线受阻，能见度降低</li>',
  '<li>容易发生水滑现象</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">雨天驾驶技巧</h4>',
  '<ul class="md-ul">',
  '<li>降低车速，加大车距</li>',
  '<li>开启雾灯或近光灯</li>',
  '<li>避免紧急制动和急打方向</li>',
  '<li>通过积水路段低速匀速通过</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">涉水驾驶</h4>',
  '<ul class="md-ul">',
  '<li>涉水前观察水深，不超过排气管高度</li>',
  '<li>挂低速挡匀速通过，中途不换挡、不停车</li>',
  '<li>涉水后连续轻踩制动，恢复制动性能</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">5.3 雾天驾驶</h3>',

  '<h4 class="know-subsection-title md-h md-h4">雾天灯光使用</h4>',
  '<ul class="md-ul">',
  '<li>开启雾灯和近光灯</li>',
  '<li>能见度低时开启危险报警闪光灯</li>',
  '<li>不得使用远光灯（会因漫反射影响视线）</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">雾天行驶技巧</h4>',
  '<ul class="md-ul">',
  '<li>减速慢行，保持安全距离</li>',
  '<li>多使用喇叭示意位置</li>',
  '<li>能见度低于50米时，最高车速不超过20km/h</li>',
  '<li>尽快驶离高速公路</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">5.4 冰雪道路驾驶</h3>',

  '<h4 class="know-subsection-title md-h md-h4">冰雪路面特点</h4>',
  '<ul class="md-ul">',
  '<li>附着力小，制动距离长</li>',
  '<li>容易打滑、侧滑</li>',
  '<li>转向困难</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">驾驶技巧</h4>',
  '<ul class="md-ul">',
  '<li>安装防滑链</li>',
  '<li>起步要轻柔，避免车轮空转</li>',
  '<li>低速行驶，保持直线</li>',
  '<li>转弯前减速，避免转弯时制动</li>',
  '<li>制动采用点刹，避免急刹</li>',
  '</ul>',
  '</section>',

  /* ============ 第六章 ============ */
  '<section class="know-chapter md-chapter" id="chapter-6">',
  '<h2 class="know-chapter-title md-h md-h2">六、紧急情况处理</h2>',

  '<h3 class="know-section-title md-h md-h3">6.1 制动失灵</h3>',

  '<h4 class="know-subsection-title md-h md-h4">处理步骤</h4>',
  '<ol class="md-ol">',
  '<li>握稳方向盘</li>',
  '<li>立即开启危险报警闪光灯</li>',
  '<li>反复踩制动踏板尝试恢复</li>',
  '<li>使用驻车制动器辅助减速</li>',
  '<li>利用发动机制动（减挡降速）</li>',
  '<li>寻找安全地带停车</li>',
  '</ol>',

  '<h4 class="know-subsection-title md-h md-h4">注意事项</h4>',
  '<ul class="md-ul">',
  '<li>不得熄火滑行</li>',
  '<li>避免碰撞行人和其他车辆</li>',
  '<li>尽量利用路侧障碍物减速</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">6.2 转向失灵</h3>',

  '<h4 class="know-subsection-title md-h md-h4">处理步骤</h4>',
  '<ol class="md-ol">',
  '<li>立即减速</li>',
  '<li>开启危险报警闪光灯</li>',
  '<li>尽量保持直线行驶</li>',
  '<li>利用制动缓慢停车</li>',
  '<li>不得紧急制动，防止侧翻</li>',
  '</ol>',

  '<h3 class="know-section-title md-h md-h3">6.3 轮胎爆胎</h3>',

  '<h4 class="know-subsection-title md-h md-h4">处理步骤</h4>',
  '<ol class="md-ol">',
  '<li>握稳方向盘，控制方向</li>',
  '<li>不得紧急制动</li>',
  '<li>缓慢减速</li>',
  '<li>开启危险报警闪光灯</li>',
  '<li>将车停至安全地点</li>',
  '</ol>',

  '<h4 class="know-subsection-title md-h md-h4">前轮爆胎</h4>',
  '<p class="md-p">前轮爆胎会严重影响方向控制，应握稳方向盘，向相反方向轻打方向修正。</p>',

  '<h4 class="know-subsection-title md-h md-h4">后轮爆胎</h4>',
  '<p class="md-p">后轮爆胎车辆会尾部摇摆，应握稳方向盘，减速停车。</p>',

  '<h3 class="know-section-title md-h md-h3">6.4 车辆起火</h3>',

  '<h4 class="know-subsection-title md-h md-h4">处理步骤</h4>',
  '<ol class="md-ol">',
  '<li>立即停车，关闭电源</li>',
  '<li>疏散乘客</li>',
  '<li>使用灭火器灭火</li>',
  '<li>火势无法控制时迅速远离并报警</li>',
  '</ol>',

  '<h4 class="know-subsection-title md-h md-h4">灭火器使用</h4>',
  '<ul class="md-ul">',
  '<li>拔出保险销</li>',
  '<li>对准火焰根部喷射</li>',
  '<li>距离火源3-4米</li>',
  '<li>顺风方向喷射</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">6.5 车辆落水</h3>',

  '<h4 class="know-subsection-title md-h md-h4">逃生步骤</h4>',
  '<ol class="md-ol">',
  '<li>保持冷静，迅速判断水深</li>',
  '<li>车辆未完全淹没时，立即打开车门或车窗逃生</li>',
  '<li>车辆已淹没时，等待车内充满水，内外压力平衡后开门</li>',
  '<li>使用安全锤破窗逃生</li>',
  '<li>逃生后迅速上浮，朝光源方向游动</li>',
  '</ol>',
  '</section>',

  /* ============ 第七章 ============ */
  '<section class="know-chapter md-chapter" id="chapter-7">',
  '<h2 class="know-chapter-title md-h md-h2">七、交通事故处理</h2>',

  '<h3 class="know-section-title md-h md-h3">7.1 事故现场处理</h3>',

  '<h4 class="know-subsection-title md-h md-h4">立即停车</h4>',
  '<ul class="md-ul">',
  '<li>开启危险报警闪光灯</li>',
  '<li>设置警告标志（普通道路50-100米，高速公路150米外）</li>',
  '<li>夜间还应开启示廓灯和后位灯</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">抢救伤员</h4>',
  '<ul class="md-ul">',
  '<li>优先抢救重伤员</li>',
  '<li>不得移动伤员，除非有起火、爆炸危险</li>',
  '<li>包扎止血，保持呼吸道通畅</li>',
  '<li>及时拨打120急救电话</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">保护现场</h4>',
  '<ul class="md-ul">',
  '<li>不得破坏事故现场</li>',
  '<li>标记车辆和伤员位置</li>',
  '<li>等待交警处理</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">7.2 轻微事故快速处理</h3>',

  '<h4 class="know-subsection-title md-h md-h4">适用条件</h4>',
  '<ul class="md-ul">',
  '<li>仅造成轻微财产损失</li>',
  '<li>未造成人员伤亡</li>',
  '<li>车辆可以移动</li>',
  '<li>事实清楚、责任明确</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">处理流程</h4>',
  '<ol class="md-ol">',
  '<li>拍照固定证据（前后、碰撞部位、车牌）</li>',
  '<li>将车辆移至不妨碍交通的地点</li>',
  '<li>协商处理或报警</li>',
  '<li>填写《当事人自行解决交通事故协议书》</li>',
  '<li>48小时内向保险公司报案</li>',
  '</ol>',

  '<h3 class="know-section-title md-h md-h3">7.3 事故责任认定</h3>',

  '<h4 class="know-subsection-title md-h md-h4">全部责任</h4>',
  '<ul class="md-ul">',
  '<li>一方当事人的违法行为导致事故</li>',
  '<li>逃逸当事人承担全部责任</li>',
  '<li>破坏现场的一方承担全部责任</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">主要责任与次要责任</h4>',
  '<ul class="md-ul">',
  '<li>双方都有过错的，根据过错程度划分主次责任</li>',
  '<li>主要责任承担70%损失</li>',
  '<li>次要责任承担30%损失</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">同等责任</h4>',
  '<ul class="md-ul">',
  '<li>双方过错程度相当的，承担同等责任</li>',
  '<li>各承担50%损失</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">7.4 肇事逃逸处罚</h3>',

  '<h4 class="know-subsection-title md-h md-h4">行政处罚</h4>',
  '<ul class="md-ul">',
  '<li>处200元以上2000元以下罚款</li>',
  '<li>15日以下行政拘留</li>',
  '<li>吊销机动车驾驶证，且终生不得重新取得</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">刑事责任</h4>',
  '<ul class="md-ul">',
  '<li>造成交通事故后逃逸，尚不构成犯罪的，从重处罚</li>',
  '<li>因逃逸致人死亡的，处7年以上有期徒刑</li>',
  '<li>交通肇事致人死亡后逃逸的，处3年以上7年以下有期徒刑</li>',
  '</ul>',
  '</section>',

  /* ============ 第八章 ============ */
  '<section class="know-chapter md-chapter" id="chapter-8">',
  '<h2 class="know-chapter-title md-h md-h2">八、车辆基本知识</h2>',

  '<h3 class="know-section-title md-h md-h3">8.1 仪表与指示灯</h3>',

  '<h4 class="know-subsection-title md-h md-h4">常见报警指示灯</h4>',
  '<ul class="md-ul">',
  '<li><strong>发动机故障灯</strong>：黄色，发动机控制系统故障</li>',
  '<li><strong>机油压力报警灯</strong>：红色，机油压力过低，应立即停车</li>',
  '<li><strong>水温报警灯</strong>：红色，发动机温度过高</li>',
  '<li><strong>充电指示灯</strong>：红色，充电系统故障</li>',
  '<li><strong>制动系统报警灯</strong>：红色，制动液不足或手刹未松</li>',
  '<li><strong>ABS报警灯</strong>：黄色，防抱死制动系统故障</li>',
  '<li><strong>安全气囊报警灯</strong>：黄色，安全气囊系统故障</li>',
  '<li><strong>胎压报警灯</strong>：黄色，轮胎气压异常</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">仪表读数</h4>',
  '<ul class="md-ul">',
  '<li><strong>转速表</strong>：发动机转速，怠速800rpm左右</li>',
  '<li><strong>车速表</strong>：车辆行驶速度</li>',
  '<li><strong>水温表</strong>：发动机冷却液温度，正常90℃左右</li>',
  '<li><strong>燃油表</strong>：油箱油量，E表示空，F表示满</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">8.2 车辆维护保养</h3>',

  '<h4 class="know-subsection-title md-h md-h4">日常检查</h4>',
  '<ul class="md-ul">',
  '<li>轮胎气压与磨损</li>',
  '<li>灯光是否齐全有效</li>',
  '<li>制动性能</li>',
  '<li>转向性能</li>',
  '<li>后视镜清洁</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">定期保养</h4>',
  '<ul class="md-ul">',
  '<li><strong>5000公里或6个月</strong>：更换机油、机滤</li>',
  '<li><strong>10000公里</strong>：更换空气滤清器</li>',
  '<li><strong>20000公里</strong>：更换火花塞、刹车油</li>',
  '<li><strong>40000公里</strong>：更换变速箱油、防冻液</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">8.3 轮胎知识</h3>',

  '<h4 class="know-subsection-title md-h md-h4">轮胎规格</h4>',
  '<p class="md-p">轮胎规格表示方法如 195/65R15 91H：</p>',
  '<ul class="md-ul">',
  '<li><strong>195</strong>：胎面宽度195mm</li>',
  '<li><strong>65</strong>：扁平比65%</li>',
  '<li><strong>R</strong>：子午线轮胎</li>',
  '<li><strong>15</strong>：轮毂直径15英寸</li>',
  '<li><strong>91</strong>：负荷指数</li>',
  '<li><strong>H</strong>：速度等级（210km/h）</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">轮胎磨损</h4>',
  '<ul class="md-ul">',
  '<li>胎面花纹深度低于1.6mm应更换</li>',
  '<li>轮胎出现鼓包、裂纹应更换</li>',
  '<li>轮胎使用超过6年应更换（无论里程）</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">轮胎气压</h4>',
  '<ul class="md-ul">',
  '<li>气压过低：油耗增加，轮胎过热</li>',
  '<li>气压过高：抓地力下降，舒适性降低</li>',
  '<li>应按厂家推荐气压充气</li>',
  '</ul>',
  '</section>',

  /* ============ 第九章 ============ */
  '<section class="know-chapter md-chapter" id="chapter-9">',
  '<h2 class="know-chapter-title md-h md-h2">九、文明驾驶</h2>',

  '<h3 class="know-section-title md-h md-h3">9.1 礼让行人</h3>',

  '<h4 class="know-subsection-title md-h md-h4">让行规定</h4>',
  '<ul class="md-ul">',
  '<li>行经人行横道应减速行驶</li>',
  '<li>遇行人正在通过人行横道应停车让行</li>',
  '<li>遇行人横过道路应避让</li>',
  '<li>转弯车辆应让直行的行人先行</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">处罚</h4>',
  '<ul class="md-ul">',
  '<li>行经人行横道未减速：记3分，罚款200元</li>',
  '<li>遇行人正在通过未停车让行：记3分，罚款200元</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">9.2 文明行车</h3>',

  '<h4 class="know-subsection-title md-h md-h4">不文明行为</h4>',
  '<ul class="md-ul">',
  '<li>乱鸣喇叭</li>',
  '<li>乱扔垃圾</li>',
  '<li>强行加塞</li>',
  '<li>开斗气车</li>',
  '<li>滥用远光灯</li>',
  '<li>车窗抛物</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">文明行为</h4>',
  '<ul class="md-ul">',
  '<li>礼让三先（先慢、先让、先停）</li>',
  '<li>规范使用灯光</li>',
  '<li>保持安全车距</li>',
  '<li>依次排队通行</li>',
  '<li>文明停车</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">9.3 特殊车辆让行</h3>',

  '<h4 class="know-subsection-title md-h md-h4">优先通行车辆</h4>',
  '<ul class="md-ul">',
  '<li>警车执行紧急任务</li>',
  '<li>消防车执行紧急任务</li>',
  '<li>救护车执行紧急任务</li>',
  '<li>工程救险车执行紧急任务</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">让行规则</h4>',
  '<ul class="md-ul">',
  '<li>遇执行紧急任务的特种车辆应主动让行</li>',
  '<li>不得穿插、超越执行紧急任务的特种车辆</li>',
  '<li>让行时不得妨碍其他车辆和行人通行</li>',
  '</ul>',
  '</section>',

  /* ============ 第十章 ============ */
  '<section class="know-chapter md-chapter" id="chapter-10">',
  '<h2 class="know-chapter-title md-h md-h2">十、考试要点速记</h2>',

  '<h3 class="know-section-title md-h md-h3">10.1 数字记忆要点</h3>',

  '<h4 class="know-subsection-title md-h md-h4">距离记忆</h4>',
  '<ul class="md-ul">',
  '<li>高速公路故障设警告标志：150米</li>',
  '<li>普通道路故障设警告标志：50-100米</li>',
  '<li>禁停距离：路口、铁路道口、急弯路、窄路、窄桥、陡坡、隧道50米内</li>',
  '<li>禁停距离：公交站、急救站、加油站、消防队30米内</li>',
  '<li>夜间会车改近光灯：150米外</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">速度记忆</h4>',
  '<ul class="md-ul">',
  '<li>高速公路最低车速：60km/h</li>',
  '<li>小型客车高速最高车速：120km/h</li>',
  '<li>其他机动车高速最高车速：100km/h</li>',
  '<li>恶劣天气高速最高车速：30km/h（能见度50米内）</li>',
  '<li>牵引故障车最高车速：30km/h</li>',
  '<li>通过铁路道口、急弯路、窄路最高车速：30km/h</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">时间记忆</h4>',
  '<ul class="md-ul">',
  '<li>驾驶证有效期：6年、10年、长期</li>',
  '<li>记分周期：12个月</li>',
  '<li>驾驶证换证提前：90日</li>',
  '<li>驾驶证补证：1日内</li>',
  '<li>轻微事故报案：48小时内</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">10.2 易混淆概念</h3>',

  '<h4 class="know-subsection-title md-h md-h4">让行规则</h4>',
  '<ul class="md-ul">',
  '<li>转弯让直行</li>',
  '<li>右转让左转</li>',
  '<li>靠山体的一方让不靠山体的一方</li>',
  '<li>下坡车让上坡车（下坡车已行至中途而上坡车未上坡时除外）</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">超车规则</h4>',
  '<ul class="md-ul">',
  '<li>不得从右侧超车</li>',
  '<li>不得在弯道、窄路、桥梁、隧道超车</li>',
  '<li>不得在铁路道口、人行横道超车</li>',
  '<li>不得在交叉路口、匝道、加速车道、减速车道超车</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">掉头规则</h4>',
  '<ul class="md-ul">',
  '<li>不得在铁路道口、交叉路口、窄路、弯道、陡坡、隧道掉头</li>',
  '<li>不得在人行横道、桥梁、高速公路掉头</li>',
  '<li>在有禁止掉头标志的地点不得掉头</li>',
  '</ul>',

  '<h3 class="know-section-title md-h md-h3">10.3 处罚记忆</h3>',

  '<h4 class="know-subsection-title md-h md-h4">吊销驾驶证</h4>',
  '<ul class="md-ul">',
  '<li>饮酒后驾驶营运车</li>',
  '<li>醉酒驾驶机动车</li>',
  '<li>将机动车交由未取得驾驶证的人驾驶</li>',
  '<li>驾驶拼装机动车或已达报废标准的机动车</li>',
  '<li>造成重大交通事故构成犯罪</li>',
  '</ul>',

  '<h4 class="know-subsection-title md-h md-h4">终生不得重新取得驾驶证</h4>',
  '<ul class="md-ul">',
  '<li>醉酒驾驶营运车</li>',
  '<li>饮酒后驾驶营运车发生重大交通事故构成犯罪</li>',
  '<li>肇事逃逸构成犯罪</li>',
  '</ul>',
  '</section>',

  /* ============ 附录 ============ */
  '<section class="know-chapter md-chapter" id="chapter-appendix">',
  '<h2 class="know-chapter-title md-h md-h2">附录：交通标志图示速查</h2>',

  '<h3 class="know-section-title md-h md-h3">警告标志（黄色三角形）</h3>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>标志名称</th><th>含义</th><th>设置位置</th>',
  '</tr></thead><tbody>',
  '<tr><td>十字交叉</td><td>前方十字交叉路口</td><td>路口前30-50米</td></tr>',
  '<tr><td>T形交叉</td><td>前方T形交叉路口</td><td>路口前30-50米</td></tr>',
  '<tr><td>急弯路</td><td>前方急弯，减速慢行</td><td>弯道前50米</td></tr>',
  '<tr><td>反向弯路</td><td>前方连续反向弯路</td><td>弯道前50米</td></tr>',
  '<tr><td>连续弯路</td><td>前方连续弯路</td><td>弯道前50米</td></tr>',
  '<tr><td>陡坡</td><td>前方陡坡</td><td>坡顶前</td></tr>',
  '<tr><td>窄路</td><td>前方道路变窄</td><td>窄路前</td></tr>',
  '<tr><td>窄桥</td><td>前方窄桥</td><td>桥前</td></tr>',
  '<tr><td>注意行人</td><td>前方行人较多</td><td>人行横道前</td></tr>',
  '<tr><td>注意儿童</td><td>前方学校或儿童活动区</td><td>学校前</td></tr>',
  '<tr><td>注意牲畜</td><td>前方可能有牲畜穿行</td><td>牲畜出没路段</td></tr>',
  '<tr><td>注意信号灯</td><td>前方有信号灯控制</td><td>信号灯前</td></tr>',
  '<tr><td>注意落石</td><td>前方可能有落石</td><td>山区路段</td></tr>',
  '<tr><td>注意横风</td><td>前方有强横风</td><td>桥梁、隧道口</td></tr>',
  '<tr><td>易滑路段</td><td>路面易滑</td><td>湿滑路段前</td></tr>',
  '<tr><td>傍山险路</td><td>傍山危险路段</td><td>山区险路前</td></tr>',
  '<tr><td>堤坝路</td><td>前方堤坝路</td><td>堤坝路前</td></tr>',
  '<tr><td>村庄</td><td>前方村庄</td><td>村庄前</td></tr>',
  '<tr><td>隧道</td><td>前方隧道</td><td>隧道前</td></tr>',
  '<tr><td>渡口</td><td>前方渡口</td><td>渡口前</td></tr>',
  '<tr><td>驼峰桥</td><td>前方驼峰桥</td><td>桥前</td></tr>',
  '<tr><td>路面不平</td><td>前方路面不平（含桥头跳车）</td><td>不平路段前</td></tr>',
  '<tr><td>过水路面</td><td>前方过水路面</td><td>过水路段前</td></tr>',
  '<tr><td>有人看守铁路道口</td><td>前方有铁路道口</td><td>道口前</td></tr>',
  '<tr><td>无人看守铁路道口</td><td>前方无人看守铁路道口</td><td>道口前</td></tr>',
  '<tr><td>注意非机动车</td><td>前方非机动车较多</td><td>非机动车道前</td></tr>',
  '<tr><td>事故易发路段</td><td>该路段事故频发</td><td>易发事故路段前</td></tr>',
  '<tr><td>慢行</td><td>减速慢行</td><td>需要减速路段</td></tr>',
  '<tr><td>注意障碍物</td><td>前方有障碍物</td><td>障碍物前</td></tr>',
  '<tr><td>施工</td><td>前方施工</td><td>施工路段前</td></tr>',
  '<tr><td>建议速度</td><td>建议行驶速度</td><td>弯道、坡道前</td></tr>',
  '</tbody></table></div>',

  '<h3 class="know-section-title md-h md-h3">易混淆标志识别详解</h3>',

  '<h4 class="know-subsection-title md-h md-h4">驼峰桥 / 路面不平 / 减速丘 / 路面低洼（高频考点）</h4>',
  '<div class="know-mnemonic md-quote">口诀：<strong>一拱空驼峰 两凸颠路面 一凸实减速丘 向下凹低洼</strong></div>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>标志名称</th><th>图形特征</th><th>含义</th><th>易混点</th>',
  '</tr></thead><tbody>',
  '<tr><td><strong>驼峰桥</strong></td><td>一个拱形，中间<strong>空心</strong>（像桥洞）</td><td>前方拱度很大、影响视距的驼峰桥，应谨慎驾驶</td><td>与减速丘混淆</td></tr>',
  '<tr><td><strong>路面不平</strong></td><td><strong>两个凸起</strong>（波浪形）</td><td>前方路面颠簸或有桥头跳车现象，应减速慢行</td><td>与驼峰桥混淆</td></tr>',
  '<tr><td><strong>减速丘</strong>（原路面高突）</td><td>一个凸起，<strong>实心</strong></td><td>前方设有减速丘，注意减速（2022新版改名）</td><td>与驼峰桥混淆</td></tr>',
  '<tr><td><strong>路面低洼</strong></td><td>中间<strong>向下凹陷</strong></td><td>前方路面低洼积水，避免颠簸损伤车辆</td><td>与驼峰桥相反</td></tr>',
  '</tbody></table></div>',
  '<blockquote class="md-quote know-tip"><strong>速记方法</strong>：',
  '驼峰桥 = 像"桥"，有桥洞（空心拱形）；',
  '路面不平 = 两个"包"（波浪起伏）；',
  '减速丘 = 一个"包"（实心凸起）；',
  '路面低洼 = 向下"凹"。',
  '</blockquote>',
  '<blockquote class="md-quote know-warning"><strong>注意</strong>：题目中问"桥头跳车"对应的是<strong>路面不平</strong>标志，不是驼峰桥！驼峰桥标志不用于提醒桥头跳车。</blockquote>',

  '<h4 class="know-subsection-title md-h md-h4">交叉路口标志识别</h4>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>标志名称</th><th>图形特征</th><th>含义</th>',
  '</tr></thead><tbody>',
  '<tr><td>十字交叉</td><td>十字形</td><td>前方十字路口</td></tr>',
  '<tr><td>T形交叉</td><td>T形</td><td>前方T形路口</td></tr>',
  '<tr><td>Y形交叉</td><td>Y形</td><td>前方Y形路口</td></tr>',
  '<tr><td>环形交叉</td><td>圆形带箭头</td><td>前方环岛</td></tr>',
  '</tbody></table></div>',

  '<h4 class="know-subsection-title md-h md-h4">铁路道口标志识别</h4>',
  '<div class="know-mnemonic md-quote">口诀：<strong>火车头无人 栅栏有人</strong></div>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>标志名称</th><th>图形特征</th><th>含义</th>',
  '</tr></thead><tbody>',
  '<tr><td>无人看守铁路道口</td><td>火车头图案</td><td>前方无人看守铁路道口</td></tr>',
  '<tr><td>有人看守铁路道口</td><td>栅栏图案</td><td>前方有人看守铁路道口</td></tr>',
  '<tr><td>距铁路道口距离</td><td>红色斜杠（1/2/3条）</td><td>距道口50/100/150米</td></tr>',
  '</tbody></table></div>',

  '<h3 class="know-section-title md-h md-h3">禁令标志（红色圆形）</h3>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>标志名称</th><th>含义</th>',
  '</tr></thead><tbody>',
  '<tr><td>禁止通行</td><td>禁止一切车辆和行人通行</td></tr>',
  '<tr><td>禁止驶入</td><td>禁止车辆驶入</td></tr>',
  '<tr><td>禁止机动车通行</td><td>禁止机动车通行</td></tr>',
  '<tr><td>禁止载货汽车通行</td><td>禁止载货汽车通行</td></tr>',
  '<tr><td>禁止小型客车通行</td><td>禁止小型客车通行</td></tr>',
  '<tr><td>禁止挂车、半挂车通行</td><td>禁止挂车、半挂车通行</td></tr>',
  '<tr><td>禁止拖拉机通行</td><td>禁止拖拉机通行</td></tr>',
  '<tr><td>禁止三轮汽车通行</td><td>禁止三轮汽车通行</td></tr>',
  '<tr><td>禁止摩托车通行</td><td>禁止摩托车通行</td></tr>',
  '<tr><td>禁止非机动车通行</td><td>禁止非机动车通行</td></tr>',
  '<tr><td>禁止畜力车通行</td><td>禁止畜力车通行</td></tr>',
  '<tr><td>禁止行人通行</td><td>禁止行人通行</td></tr>',
  '<tr><td>禁止向左转弯</td><td>禁止向左转弯</td></tr>',
  '<tr><td>禁止向右转弯</td><td>禁止向右转弯</td></tr>',
  '<tr><td>禁止直行</td><td>禁止直行</td></tr>',
  '<tr><td>禁止向左向右转弯</td><td>禁止向左和向右转弯</td></tr>',
  '<tr><td>禁止直行和向左转弯</td><td>禁止直行和向左转弯</td></tr>',
  '<tr><td>禁止直行和向右转弯</td><td>禁止直行和向右转弯</td></tr>',
  '<tr><td>禁止掉头</td><td>禁止掉头</td></tr>',
  '<tr><td>禁止超车</td><td>禁止超车</td></tr>',
  '<tr><td>解除禁止超车</td><td>解除禁止超车</td></tr>',
  '<tr><td>禁止停车</td><td>禁止停车</td></tr>',
  '<tr><td>禁止长时间停车</td><td>禁止长时间停车</td></tr>',
  '<tr><td>禁止鸣喇叭</td><td>禁止鸣喇叭</td></tr>',
  '<tr><td>限制宽度</td><td>限制车辆宽度</td></tr>',
  '<tr><td>限制高度</td><td>限制车辆高度</td></tr>',
  '<tr><td>限制质量</td><td>限制车辆质量</td></tr>',
  '<tr><td>限制轴重</td><td>限制车辆轴重</td></tr>',
  '<tr><td>限制速度</td><td>限制最高速度</td></tr>',
  '<tr><td>解除限制速度</td><td>解除限制速度</td></tr>',
  '<tr><td>停车检查</td><td>停车接受检查</td></tr>',
  '<tr><td>停车让行</td><td>停车让行</td></tr>',
  '<tr><td>减速让行</td><td>减速让行</td></tr>',
  '<tr><td>会车让行</td><td>会车时让行</td></tr>',
  '</tbody></table></div>',

  '<h3 class="know-section-title md-h md-h3">指示标志（蓝色）</h3>',
  '<div class="md-table-wrap"><table class="know-table md-table"><thead><tr>',
  '<th>标志名称</th><th>含义</th>',
  '</tr></thead><tbody>',
  '<tr><td>直行</td><td>只准直行</td></tr>',
  '<tr><td>向左转弯</td><td>只准向左转弯</td></tr>',
  '<tr><td>向右转弯</td><td>只准向右转弯</td></tr>',
  '<tr><td>直行和向左转弯</td><td>直行和向左转弯</td></tr>',
  '<tr><td>直行和向右转弯</td><td>直行和向右转弯</td></tr>',
  '<tr><td>向左和向右转弯</td><td>向左和向右转弯</td></tr>',
  '<tr><td>靠右侧道路行驶</td><td>靠右侧道路行驶</td></tr>',
  '<tr><td>靠左侧道路行驶</td><td>靠左侧道路行驶</td></tr>',
  '<tr><td>立交直行和左转弯行驶</td><td>立交直行和左转弯</td></tr>',
  '<tr><td>立交直行和右转弯行驶</td><td>立交直行和右转弯</td></tr>',
  '<tr><td>单行路（向左或向右）</td><td>单行路</td></tr>',
  '<tr><td>单行路（直行）</td><td>单行路</td></tr>',
  '<tr><td>步行</td><td>步行街</td></tr>',
  '<tr><td>鸣喇叭</td><td>鸣喇叭</td></tr>',
  '<tr><td>最低限速</td><td>最低限速</td></tr>',
  '<tr><td>干路先行</td><td>干路先行</td></tr>',
  '<tr><td>会车先行</td><td>会车先行</td></tr>',
  '<tr><td>人行横道</td><td>人行横道</td></tr>',
  '<tr><td>右转车道</td><td>右转车道</td></tr>',
  '<tr><td>直行车道</td><td>直行车道</td></tr>',
  '<tr><td>直行和右转合用车道</td><td>直行和右转合用车道</td></tr>',
  '<tr><td>分向行驶车道</td><td>分向行驶车道</td></tr>',
  '<tr><td>公交线路专用车道</td><td>公交线路专用车道</td></tr>',
  '<tr><td>机动车行驶</td><td>机动车行驶</td></tr>',
  '<tr><td>机动车车道</td><td>机动车车道</td></tr>',
  '<tr><td>非机动车行驶</td><td>非机动车行驶</td></tr>',
  '<tr><td>非机动车车道</td><td>非机动车车道</td></tr>',
  '<tr><td>允许掉头</td><td>允许掉头</td></tr>',
  '</tbody></table></div>',
  '</section>',

  /* ============ 结语 ============ */
  '<section class="know-chapter md-chapter" id="chapter-epilogue">',
  '<h2 class="know-chapter-title md-h md-h2">结语</h2>',
  '<p class="md-p">本教学文档基于2026年最新驾考大纲编写，涵盖科目一考试全部知识点。建议结合题库练习、模拟考试、口诀速记同步学习，系统掌握交通法规与安全驾驶知识，顺利通过科目一考试，为安全文明驾驶奠定基础。</p>',
  '<blockquote class="md-quote know-tip"><strong>学习建议</strong>',
  '<ol class="md-ol" style="margin-top:6px">',
  '<li>先通读本文档，建立知识框架</li>',
  '<li>结合题库练习，巩固知识点</li>',
  '<li>使用口诀速记，强化记忆</li>',
  '<li>进行模拟考试，检验学习成果</li>',
  '<li>针对薄弱环节，重点复习</li>',
  '</ol>',
  '</blockquote>',
  '</section>'
].join('\n');

/* 将全局变量挂载到 window，供 app.js 读取 */
if (typeof window !== 'undefined') {
  window.KNOWLEDGE_HTML = KNOWLEDGE_HTML;
}
